// Code generated by MockGen. DO NOT EDIT.
// Source: dep.go
//
// Generated by this command:
//
//	mockgen -source=dep.go -destination=./mocks/nav_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	biz "github.com/seanbit/kratos/template/internal/biz"
	gomock "go.uber.org/mock/gomock"
)

// MockIAlarmRepo is a mock of IAlarmRepo interface.
type MockIAlarmRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAlarmRepoMockRecorder
	isgomock struct{}
}

// MockIAlarmRepoMockRecorder is the mock recorder for MockIAlarmRepo.
type MockIAlarmRepoMockRecorder struct {
	mock *MockIAlarmRepo
}

// NewMockIAlarmRepo creates a new mock instance.
func NewMockIAlarmRepo(ctrl *gomock.Controller) *MockIAlarmRepo {
	mock := &MockIAlarmRepo{ctrl: ctrl}
	mock.recorder = &MockIAlarmRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAlarmRepo) EXPECT() *MockIAlarmRepoMockRecorder {
	return m.recorder
}

// SendBizMessage mocks base method.
func (m *MockIAlarmRepo) SendBizMessage(ctx context.Context, title, info string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendBizMessage", ctx, title, info)
}

// SendBizMessage indicates an expected call of SendBizMessage.
func (mr *MockIAlarmRepoMockRecorder) SendBizMessage(ctx, title, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBizMessage", reflect.TypeOf((*MockIAlarmRepo)(nil).SendBizMessage), ctx, title, info)
}

// SendMessage mocks base method.
func (m *MockIAlarmRepo) SendMessage(ctx context.Context, platform, title, info string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendMessage", ctx, platform, title, info)
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockIAlarmRepoMockRecorder) SendMessage(ctx, platform, title, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockIAlarmRepo)(nil).SendMessage), ctx, platform, title, info)
}

// MockIGeoIp is a mock of IGeoIp interface.
type MockIGeoIp struct {
	ctrl     *gomock.Controller
	recorder *MockIGeoIpMockRecorder
	isgomock struct{}
}

// MockIGeoIpMockRecorder is the mock recorder for MockIGeoIp.
type MockIGeoIpMockRecorder struct {
	mock *MockIGeoIp
}

// NewMockIGeoIp creates a new mock instance.
func NewMockIGeoIp(ctrl *gomock.Controller) *MockIGeoIp {
	mock := &MockIGeoIp{ctrl: ctrl}
	mock.recorder = &MockIGeoIpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGeoIp) EXPECT() *MockIGeoIpMockRecorder {
	return m.recorder
}

// GetCountryFromIp mocks base method.
func (m *MockIGeoIp) GetCountryFromIp(ctx context.Context, ip string) (*biz.GeoCountry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountryFromIp", ctx, ip)
	ret0, _ := ret[0].(*biz.GeoCountry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountryFromIp indicates an expected call of GetCountryFromIp.
func (mr *MockIGeoIpMockRecorder) GetCountryFromIp(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountryFromIp", reflect.TypeOf((*MockIGeoIp)(nil).GetCountryFromIp), ctx, ip)
}

// MockINavService is a mock of INavService interface.
type MockINavService struct {
	ctrl     *gomock.Controller
	recorder *MockINavServiceMockRecorder
	isgomock struct{}
}

// MockINavServiceMockRecorder is the mock recorder for MockINavService.
type MockINavServiceMockRecorder struct {
	mock *MockINavService
}

// NewMockINavService creates a new mock instance.
func NewMockINavService(ctrl *gomock.Controller) *MockINavService {
	mock := &MockINavService{ctrl: ctrl}
	mock.recorder = &MockINavServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINavService) EXPECT() *MockINavServiceMockRecorder {
	return m.recorder
}

// GetNav mocks base method.
func (m *MockINavService) GetNav() (*biz.NavInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNav")
	ret0, _ := ret[0].(*biz.NavInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNav indicates an expected call of GetNav.
func (mr *MockINavServiceMockRecorder) GetNav() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNav", reflect.TypeOf((*MockINavService)(nil).GetNav))
}
