// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: event.auth.proto

package event

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The event message for user login
type UserLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      string                 `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	IssueToken    string                 `protobuf:"bytes,4,opt,name=issue_token,json=issueToken,proto3" json:"issue_token,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogin) Reset() {
	*x = UserLogin{}
	mi := &file_event_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogin) ProtoMessage() {}

func (x *UserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_event_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogin.ProtoReflect.Descriptor instead.
func (*UserLogin) Descriptor() ([]byte, []int) {
	return file_event_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserLogin) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UserLogin) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLogin) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserLogin) GetIssueToken() string {
	if x != nil {
		return x.IssueToken
	}
	return ""
}

func (x *UserLogin) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_event_auth_proto protoreflect.FileDescriptor

const file_event_auth_proto_rawDesc = "" +
	"\n" +
	"\x10event.auth.proto\x12\x05event\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\tUserLogin\x12\x1b\n" +
	"\tauth_type\x18\x01 \x01(\tR\bauthType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1f\n" +
	"\vissue_token\x18\x04 \x01(\tR\n" +
	"issueToken\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB5Z3github.com/carv-protocol/kratos-ddd/api/event;eventb\x06proto3"

var (
	file_event_auth_proto_rawDescOnce sync.Once
	file_event_auth_proto_rawDescData []byte
)

func file_event_auth_proto_rawDescGZIP() []byte {
	file_event_auth_proto_rawDescOnce.Do(func() {
		file_event_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_auth_proto_rawDesc), len(file_event_auth_proto_rawDesc)))
	})
	return file_event_auth_proto_rawDescData
}

var file_event_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_auth_proto_goTypes = []any{
	(*UserLogin)(nil),             // 0: event.UserLogin
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_event_auth_proto_depIdxs = []int32{
	1, // 0: event.UserLogin.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_auth_proto_init() }
func file_event_auth_proto_init() {
	if File_event_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_auth_proto_rawDesc), len(file_event_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_auth_proto_goTypes,
		DependencyIndexes: file_event_auth_proto_depIdxs,
		MessageInfos:      file_event_auth_proto_msgTypes,
	}.Build()
	File_event_auth_proto = out.File
	file_event_auth_proto_goTypes = nil
	file_event_auth_proto_depIdxs = nil
}
