// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: auth.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLoginSignTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 区块链类型：1 evm/
	BlockchainType BlockChainType `protobuf:"varint,1,opt,name=blockchain_type,json=blockchainType,proto3,enum=web.BlockChainType" json:"blockchain_type,omitempty"`
	// 钱包地址
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginSignTextRequest) Reset() {
	*x = GetLoginSignTextRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginSignTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginSignTextRequest) ProtoMessage() {}

func (x *GetLoginSignTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginSignTextRequest.ProtoReflect.Descriptor instead.
func (*GetLoginSignTextRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetLoginSignTextRequest) GetBlockchainType() BlockChainType {
	if x != nil {
		return x.BlockchainType
	}
	return BlockChainType__BLOCK_CHAIN_TYPE_NONE_
}

func (x *GetLoginSignTextRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetLoginSignTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginSignTextResponse) Reset() {
	*x = GetLoginSignTextResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginSignTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginSignTextResponse) ProtoMessage() {}

func (x *GetLoginSignTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginSignTextResponse.ProtoReflect.Descriptor instead.
func (*GetLoginSignTextResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetLoginSignTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// The request message containing the user's name.
type LoginByWalletRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 区块链类型：1 evm/
	BlockchainType BlockChainType `protobuf:"varint,1,opt,name=blockchain_type,json=blockchainType,proto3,enum=web.BlockChainType" json:"blockchain_type,omitempty"`
	// 签名原文
	OriginText string `protobuf:"bytes,2,opt,name=origin_text,json=originText,proto3" json:"origin_text,omitempty"` // origin text to signature
	// 签名
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // signature by web3 wallet
	// 要验证的钱包地址
	Address       string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"` // wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByWalletRequest) Reset() {
	*x = LoginByWalletRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByWalletRequest) ProtoMessage() {}

func (x *LoginByWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByWalletRequest.ProtoReflect.Descriptor instead.
func (*LoginByWalletRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginByWalletRequest) GetBlockchainType() BlockChainType {
	if x != nil {
		return x.BlockchainType
	}
	return BlockChainType__BLOCK_CHAIN_TYPE_NONE_
}

func (x *LoginByWalletRequest) GetOriginText() string {
	if x != nil {
		return x.OriginText
	}
	return ""
}

func (x *LoginByWalletRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *LoginByWalletRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The response message containing the greetings
type LoginByWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByWalletResponse) Reset() {
	*x = LoginByWalletResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByWalletResponse) ProtoMessage() {}

func (x *LoginByWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByWalletResponse.ProtoReflect.Descriptor instead.
func (*LoginByWalletResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginByWalletResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x0fconstants.proto\"\x86\x01\n" +
	"\x17GetLoginSignTextRequest\x12F\n" +
	"\x0fblockchain_type\x18\x01 \x01(\x0e2\x13.web.BlockChainTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0eblockchainType\x12#\n" +
	"\aaddress\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10 \x18@R\aaddress\".\n" +
	"\x18GetLoginSignTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xda\x01\n" +
	"\x14LoginByWalletRequest\x12F\n" +
	"\x0fblockchain_type\x18\x01 \x01(\x0e2\x13.web.BlockChainTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0eblockchainType\x12+\n" +
	"\vorigin_text\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x10R\n" +
	"originText\x12(\n" +
	"\tsignature\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10 \x18\x80\x02R\tsignature\x12#\n" +
	"\aaddress\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10 \x18@R\aaddress\"-\n" +
	"\x15LoginByWalletResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xe2\x01\n" +
	"\x04Auth\x12e\n" +
	"\rLoginByWallet\x12\x19.web.LoginByWalletRequest\x1a\x1a.web.LoginByWalletResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/auth/login/wallet\x12s\n" +
	"\x15GetLoginSignatureText\x12\x1c.web.GetLoginSignTextRequest\x1a\x1d.web.GetLoginSignTextResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/auth/login/sign_textB1Z/github.com/carv-protocol/kratos-ddd/api/web;webb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_proto_goTypes = []any{
	(*GetLoginSignTextRequest)(nil),  // 0: web.GetLoginSignTextRequest
	(*GetLoginSignTextResponse)(nil), // 1: web.GetLoginSignTextResponse
	(*LoginByWalletRequest)(nil),     // 2: web.LoginByWalletRequest
	(*LoginByWalletResponse)(nil),    // 3: web.LoginByWalletResponse
	(BlockChainType)(0),              // 4: web.BlockChainType
}
var file_auth_proto_depIdxs = []int32{
	4, // 0: web.GetLoginSignTextRequest.blockchain_type:type_name -> web.BlockChainType
	4, // 1: web.LoginByWalletRequest.blockchain_type:type_name -> web.BlockChainType
	2, // 2: web.Auth.LoginByWallet:input_type -> web.LoginByWalletRequest
	0, // 3: web.Auth.GetLoginSignatureText:input_type -> web.GetLoginSignTextRequest
	3, // 4: web.Auth.LoginByWallet:output_type -> web.LoginByWalletResponse
	1, // 5: web.Auth.GetLoginSignatureText:output_type -> web.GetLoginSignTextResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_constants_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
