// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth.proto

package web

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetLoginSignTextRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLoginSignTextRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLoginSignTextRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLoginSignTextRequestMultiError, or nil if none found.
func (m *GetLoginSignTextRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLoginSignTextRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlockchainType

	if l := utf8.RuneCountInString(m.GetAddress()); l < 32 || l > 64 {
		err := GetLoginSignTextRequestValidationError{
			field:  "Address",
			reason: "value length must be between 32 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetLoginSignTextRequestMultiError(errors)
	}

	return nil
}

// GetLoginSignTextRequestMultiError is an error wrapping multiple validation
// errors returned by GetLoginSignTextRequest.ValidateAll() if the designated
// constraints aren't met.
type GetLoginSignTextRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLoginSignTextRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLoginSignTextRequestMultiError) AllErrors() []error { return m }

// GetLoginSignTextRequestValidationError is the validation error returned by
// GetLoginSignTextRequest.Validate if the designated constraints aren't met.
type GetLoginSignTextRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLoginSignTextRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLoginSignTextRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLoginSignTextRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLoginSignTextRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLoginSignTextRequestValidationError) ErrorName() string {
	return "GetLoginSignTextRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetLoginSignTextRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLoginSignTextRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLoginSignTextRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLoginSignTextRequestValidationError{}

// Validate checks the field values on GetLoginSignTextResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLoginSignTextResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLoginSignTextResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLoginSignTextResponseMultiError, or nil if none found.
func (m *GetLoginSignTextResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLoginSignTextResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Text

	if len(errors) > 0 {
		return GetLoginSignTextResponseMultiError(errors)
	}

	return nil
}

// GetLoginSignTextResponseMultiError is an error wrapping multiple validation
// errors returned by GetLoginSignTextResponse.ValidateAll() if the designated
// constraints aren't met.
type GetLoginSignTextResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLoginSignTextResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLoginSignTextResponseMultiError) AllErrors() []error { return m }

// GetLoginSignTextResponseValidationError is the validation error returned by
// GetLoginSignTextResponse.Validate if the designated constraints aren't met.
type GetLoginSignTextResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLoginSignTextResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLoginSignTextResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLoginSignTextResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLoginSignTextResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLoginSignTextResponseValidationError) ErrorName() string {
	return "GetLoginSignTextResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetLoginSignTextResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLoginSignTextResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLoginSignTextResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLoginSignTextResponseValidationError{}

// Validate checks the field values on LoginByWalletRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LoginByWalletRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginByWalletRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoginByWalletRequestMultiError, or nil if none found.
func (m *LoginByWalletRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginByWalletRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlockchainType

	if l := utf8.RuneCountInString(m.GetOriginText()); l < 1 || l > 2048 {
		err := LoginByWalletRequestValidationError{
			field:  "OriginText",
			reason: "value length must be between 1 and 2048 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSignature()); l < 32 || l > 256 {
		err := LoginByWalletRequestValidationError{
			field:  "Signature",
			reason: "value length must be between 32 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetAddress()); l < 32 || l > 64 {
		err := LoginByWalletRequestValidationError{
			field:  "Address",
			reason: "value length must be between 32 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LoginByWalletRequestMultiError(errors)
	}

	return nil
}

// LoginByWalletRequestMultiError is an error wrapping multiple validation
// errors returned by LoginByWalletRequest.ValidateAll() if the designated
// constraints aren't met.
type LoginByWalletRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginByWalletRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginByWalletRequestMultiError) AllErrors() []error { return m }

// LoginByWalletRequestValidationError is the validation error returned by
// LoginByWalletRequest.Validate if the designated constraints aren't met.
type LoginByWalletRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginByWalletRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginByWalletRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginByWalletRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginByWalletRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginByWalletRequestValidationError) ErrorName() string {
	return "LoginByWalletRequestValidationError"
}

// Error satisfies the builtin error interface
func (e LoginByWalletRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginByWalletRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginByWalletRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginByWalletRequestValidationError{}

// Validate checks the field values on LoginByWalletResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LoginByWalletResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginByWalletResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoginByWalletResponseMultiError, or nil if none found.
func (m *LoginByWalletResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginByWalletResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return LoginByWalletResponseMultiError(errors)
	}

	return nil
}

// LoginByWalletResponseMultiError is an error wrapping multiple validation
// errors returned by LoginByWalletResponse.ValidateAll() if the designated
// constraints aren't met.
type LoginByWalletResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginByWalletResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginByWalletResponseMultiError) AllErrors() []error { return m }

// LoginByWalletResponseValidationError is the validation error returned by
// LoginByWalletResponse.Validate if the designated constraints aren't met.
type LoginByWalletResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginByWalletResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginByWalletResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginByWalletResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginByWalletResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginByWalletResponseValidationError) ErrorName() string {
	return "LoginByWalletResponseValidationError"
}

// Error satisfies the builtin error interface
func (e LoginByWalletResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginByWalletResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginByWalletResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginByWalletResponseValidationError{}
