// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: auth.proto

package web

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_LoginByWallet_FullMethodName         = "/web.Auth/LoginByWallet"
	Auth_GetLoginSignatureText_FullMethodName = "/web.Auth/GetLoginSignatureText"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The auth service definition.
type AuthClient interface {
	// Login by web3 wallet
	LoginByWallet(ctx context.Context, in *LoginByWalletRequest, opts ...grpc.CallOption) (*LoginByWalletResponse, error)
	// Get login signature text
	GetLoginSignatureText(ctx context.Context, in *GetLoginSignTextRequest, opts ...grpc.CallOption) (*GetLoginSignTextResponse, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) LoginByWallet(ctx context.Context, in *LoginByWalletRequest, opts ...grpc.CallOption) (*LoginByWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginByWalletResponse)
	err := c.cc.Invoke(ctx, Auth_LoginByWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetLoginSignatureText(ctx context.Context, in *GetLoginSignTextRequest, opts ...grpc.CallOption) (*GetLoginSignTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoginSignTextResponse)
	err := c.cc.Invoke(ctx, Auth_GetLoginSignatureText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
//
// The auth service definition.
type AuthServer interface {
	// Login by web3 wallet
	LoginByWallet(context.Context, *LoginByWalletRequest) (*LoginByWalletResponse, error)
	// Get login signature text
	GetLoginSignatureText(context.Context, *GetLoginSignTextRequest) (*GetLoginSignTextResponse, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) LoginByWallet(context.Context, *LoginByWalletRequest) (*LoginByWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByWallet not implemented")
}
func (UnimplementedAuthServer) GetLoginSignatureText(context.Context, *GetLoginSignTextRequest) (*GetLoginSignTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginSignatureText not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call pancis, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_LoginByWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginByWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_LoginByWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginByWallet(ctx, req.(*LoginByWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetLoginSignatureText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoginSignTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetLoginSignatureText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_GetLoginSignatureText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetLoginSignatureText(ctx, req.(*GetLoginSignTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginByWallet",
			Handler:    _Auth_LoginByWallet_Handler,
		},
		{
			MethodName: "GetLoginSignatureText",
			Handler:    _Auth_GetLoginSignatureText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
