// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package web

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 占位符，避免第一个枚举值为0
func Is(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason__.String() && e.Code == 500
}

// 占位符，避免第一个枚举值为0
func Error(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason__.String(), fmt.Sprintf(format, args...))
}

func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAMS.String() && e.Code == 400
}

func ErrorInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAMS.String(), fmt.Sprintf(format, args...))
}

func IsContentMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CONTENT_MISSING.String() && e.Code == 400
}

func ErrorContentMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsAuthLoginExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_LOGIN_EXPIRED.String() && e.Code == 401
}

func ErrorAuthLoginExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_AUTH_LOGIN_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsAuthLoginTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_LOGIN_TOKEN_INVALID.String() && e.Code == 401
}

func ErrorAuthLoginTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_AUTH_LOGIN_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsAuthBlockChainTypeNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_BLOCK_CHAIN_TYPE_NOT_SUPPORT.String() && e.Code == 400
}

func ErrorAuthBlockChainTypeNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_AUTH_BLOCK_CHAIN_TYPE_NOT_SUPPORT.String(), fmt.Sprintf(format, args...))
}

func IsAuthSignatureTextInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_SIGNATURE_TEXT_INVALID.String() && e.Code == 400
}

func ErrorAuthSignatureTextInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_AUTH_SIGNATURE_TEXT_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsAuthSignatureTextExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_SIGNATURE_TEXT_EXPIRED.String() && e.Code == 400
}

func ErrorAuthSignatureTextExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_AUTH_SIGNATURE_TEXT_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_ALREADY_EXISTS.String() && e.Code == 404
}

func ErrorUserAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}
