// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: code.proto

package web

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason__                                 ErrorReason = 0 // 占位符，避免第一个枚举值为0
	ErrorReason_INVALID_PARAMS                    ErrorReason = 400
	ErrorReason_CONTENT_MISSING                   ErrorReason = 10000
	ErrorReason_AUTH_LOGIN_EXPIRED                ErrorReason = 10001
	ErrorReason_AUTH_LOGIN_TOKEN_INVALID          ErrorReason = 10005
	ErrorReason_AUTH_BLOCK_CHAIN_TYPE_NOT_SUPPORT ErrorReason = 10002
	ErrorReason_AUTH_SIGNATURE_TEXT_INVALID       ErrorReason = 10003
	ErrorReason_AUTH_SIGNATURE_TEXT_EXPIRED       ErrorReason = 10004
	ErrorReason_USER_NOT_FOUND                    ErrorReason = 10101
	ErrorReason_USER_ALREADY_EXISTS               ErrorReason = 10102
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:     "_",
		400:   "INVALID_PARAMS",
		10000: "CONTENT_MISSING",
		10001: "AUTH_LOGIN_EXPIRED",
		10005: "AUTH_LOGIN_TOKEN_INVALID",
		10002: "AUTH_BLOCK_CHAIN_TYPE_NOT_SUPPORT",
		10003: "AUTH_SIGNATURE_TEXT_INVALID",
		10004: "AUTH_SIGNATURE_TEXT_EXPIRED",
		10101: "USER_NOT_FOUND",
		10102: "USER_ALREADY_EXISTS",
	}
	ErrorReason_value = map[string]int32{
		"_":                                 0,
		"INVALID_PARAMS":                    400,
		"CONTENT_MISSING":                   10000,
		"AUTH_LOGIN_EXPIRED":                10001,
		"AUTH_LOGIN_TOKEN_INVALID":          10005,
		"AUTH_BLOCK_CHAIN_TYPE_NOT_SUPPORT": 10002,
		"AUTH_SIGNATURE_TEXT_INVALID":       10003,
		"AUTH_SIGNATURE_TEXT_EXPIRED":       10004,
		"USER_NOT_FOUND":                    10101,
		"USER_ALREADY_EXISTS":               10102,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_code_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_code_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_code_proto_rawDescGZIP(), []int{0}
}

var File_code_proto protoreflect.FileDescriptor

const file_code_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"code.proto\x12\x03web\x1a\x13errors/errors.proto*\xce\x02\n" +
	"\vErrorReason\x12\x05\n" +
	"\x01_\x10\x00\x12\x19\n" +
	"\x0eINVALID_PARAMS\x10\x90\x03\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x0fCONTENT_MISSING\x10\x90N\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x12AUTH_LOGIN_EXPIRED\x10\x91N\x1a\x04\xa8E\x91\x03\x12#\n" +
	"\x18AUTH_LOGIN_TOKEN_INVALID\x10\x95N\x1a\x04\xa8E\x91\x03\x12,\n" +
	"!AUTH_BLOCK_CHAIN_TYPE_NOT_SUPPORT\x10\x92N\x1a\x04\xa8E\x90\x03\x12&\n" +
	"\x1bAUTH_SIGNATURE_TEXT_INVALID\x10\x93N\x1a\x04\xa8E\x90\x03\x12&\n" +
	"\x1bAUTH_SIGNATURE_TEXT_EXPIRED\x10\x94N\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\x0eUSER_NOT_FOUND\x10\xf5N\x1a\x04\xa8E\x94\x03\x12\x1e\n" +
	"\x13USER_ALREADY_EXISTS\x10\xf6N\x1a\x04\xa8E\x94\x03\x1a\x04\xa0E\xf4\x03B1Z/github.com/carv-protocol/kratos-ddd/api/web;webb\x06proto3"

var (
	file_code_proto_rawDescOnce sync.Once
	file_code_proto_rawDescData []byte
)

func file_code_proto_rawDescGZIP() []byte {
	file_code_proto_rawDescOnce.Do(func() {
		file_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)))
	})
	return file_code_proto_rawDescData
}

var file_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_code_proto_goTypes = []any{
	(ErrorReason)(0), // 0: web.ErrorReason
}
var file_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_init() }
func file_code_proto_init() {
	if File_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code_proto_goTypes,
		DependencyIndexes: file_code_proto_depIdxs,
		EnumInfos:         file_code_proto_enumTypes,
	}.Build()
	File_code_proto = out.File
	file_code_proto_goTypes = nil
	file_code_proto_depIdxs = nil
}
