// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: constants.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockChainType int32

const (
	BlockChainType__BLOCK_CHAIN_TYPE_NONE_ BlockChainType = 0
	BlockChainType_BLOCK_CHAIN_TYPE_EVM    BlockChainType = 1
)

// Enum value maps for BlockChainType.
var (
	BlockChainType_name = map[int32]string{
		0: "_BLOCK_CHAIN_TYPE_NONE_",
		1: "BLOCK_CHAIN_TYPE_EVM",
	}
	BlockChainType_value = map[string]int32{
		"_BLOCK_CHAIN_TYPE_NONE_": 0,
		"BLOCK_CHAIN_TYPE_EVM":    1,
	}
)

func (x BlockChainType) Enum() *BlockChainType {
	p := new(BlockChainType)
	*p = x
	return p
}

func (x BlockChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[0].Descriptor()
}

func (BlockChainType) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[0]
}

func (x BlockChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockChainType.Descriptor instead.
func (BlockChainType) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{0}
}

var File_constants_proto protoreflect.FileDescriptor

const file_constants_proto_rawDesc = "" +
	"\n" +
	"\x0fconstants.proto\x12\x03web*G\n" +
	"\x0eBlockChainType\x12\x1b\n" +
	"\x17_BLOCK_CHAIN_TYPE_NONE_\x10\x00\x12\x18\n" +
	"\x14BLOCK_CHAIN_TYPE_EVM\x10\x01B1Z/github.com/carv-protocol/kratos-ddd/api/web;webb\x06proto3"

var (
	file_constants_proto_rawDescOnce sync.Once
	file_constants_proto_rawDescData []byte
)

func file_constants_proto_rawDescGZIP() []byte {
	file_constants_proto_rawDescOnce.Do(func() {
		file_constants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constants_proto_rawDesc), len(file_constants_proto_rawDesc)))
	})
	return file_constants_proto_rawDescData
}

var file_constants_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constants_proto_goTypes = []any{
	(BlockChainType)(0), // 0: web.BlockChainType
}
var file_constants_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constants_proto_init() }
func file_constants_proto_init() {
	if File_constants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constants_proto_rawDesc), len(file_constants_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constants_proto_goTypes,
		DependencyIndexes: file_constants_proto_depIdxs,
		EnumInfos:         file_constants_proto_enumTypes,
	}.Build()
	File_constants_proto = out.File
	file_constants_proto_goTypes = nil
	file_constants_proto_depIdxs = nil
}
