// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.0
// source: probe.proto

package web

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProbehealthLive = "/web.Probe/healthLive"
const OperationProbehealthReady = "/web.Probe/healthReady"
const OperationProbehealthStatus = "/web.Probe/healthStatus"

type ProbeHTTPServer interface {
	// HealthLive for liveness probe
	HealthLive(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// HealthReady for readiness probe
	// 这里示范使用 google.protobuf.Struct 从gin这样的web框架迁移代码直接重用原来的接口struct定义
	// 避免从go struct到pb message的转换。
	// 不过，还是建议使用pb来定义接口, 这样接口更易于维护
	HealthReady(context.Context, *structpb.Struct) (*ReadinessProbeResponse, error)
	// HealthStatus for health detail probe
	HealthStatus(context.Context, *emptypb.Empty) (*HealthStatusResponse, error)
}

func RegisterProbeHTTPServer(s *http.Server, srv ProbeHTTPServer) {
	r := s.Route("/")
	r.GET("/health", _Probe_HealthStatus0_HTTP_Handler(srv))
	r.GET("/health/live", _Probe_HealthLive0_HTTP_Handler(srv))
	r.GET("/health/ready", _Probe_HealthReady0_HTTP_Handler(srv))
}

func _Probe_HealthStatus0_HTTP_Handler(srv ProbeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProbehealthStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HealthStatus(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _Probe_HealthLive0_HTTP_Handler(srv ProbeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProbehealthLive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HealthLive(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Probe_HealthReady0_HTTP_Handler(srv ProbeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in structpb.Struct
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProbehealthReady)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HealthReady(ctx, req.(*structpb.Struct))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReadinessProbeResponse)
		return ctx.Result(200, reply)
	}
}

type ProbeHTTPClient interface {
	// HealthLive for liveness probe
	HealthLive(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// HealthReady for readiness probe
	// 这里示范使用 google.protobuf.Struct 从gin这样的web框架迁移代码直接重用原来的接口struct定义
	// 避免从go struct到pb message的转换。
	// 不过，还是建议使用pb来定义接口, 这样接口更易于维护
	HealthReady(ctx context.Context, req *structpb.Struct, opts ...http.CallOption) (rsp *ReadinessProbeResponse, err error)
	// HealthStatus for health detail probe
	HealthStatus(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *HealthStatusResponse, err error)
}

type ProbeHTTPClientImpl struct {
	cc *http.Client
}

func NewProbeHTTPClient(client *http.Client) ProbeHTTPClient {
	return &ProbeHTTPClientImpl{client}
}

// HealthLive for liveness probe
func (c *ProbeHTTPClientImpl) HealthLive(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/health/live"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProbehealthLive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HealthReady for readiness probe
// 这里示范使用 google.protobuf.Struct 从gin这样的web框架迁移代码直接重用原来的接口struct定义
// 避免从go struct到pb message的转换。
// 不过，还是建议使用pb来定义接口, 这样接口更易于维护
func (c *ProbeHTTPClientImpl) HealthReady(ctx context.Context, in *structpb.Struct, opts ...http.CallOption) (*ReadinessProbeResponse, error) {
	var out ReadinessProbeResponse
	pattern := "/health/ready"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProbehealthReady))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HealthStatus for health detail probe
func (c *ProbeHTTPClientImpl) HealthStatus(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*HealthStatusResponse, error) {
	var out HealthStatusResponse
	pattern := "/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProbehealthStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
