// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: probe.proto

package web

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReadinessProbeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReadinessProbeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadinessProbeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReadinessProbeResponseMultiError, or nil if none found.
func (m *ReadinessProbeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadinessProbeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return ReadinessProbeResponseMultiError(errors)
	}

	return nil
}

// ReadinessProbeResponseMultiError is an error wrapping multiple validation
// errors returned by ReadinessProbeResponse.ValidateAll() if the designated
// constraints aren't met.
type ReadinessProbeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadinessProbeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadinessProbeResponseMultiError) AllErrors() []error { return m }

// ReadinessProbeResponseValidationError is the validation error returned by
// ReadinessProbeResponse.Validate if the designated constraints aren't met.
type ReadinessProbeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadinessProbeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadinessProbeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadinessProbeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadinessProbeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadinessProbeResponseValidationError) ErrorName() string {
	return "ReadinessProbeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReadinessProbeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadinessProbeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadinessProbeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadinessProbeResponseValidationError{}

// Validate checks the field values on HealthStatusResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthStatusResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthStatusResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthStatusResponseMultiError, or nil if none found.
func (m *HealthStatusResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthStatusResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	{
		sorted_keys := make([]string, len(m.GetComponents()))
		i := 0
		for key := range m.GetComponents() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetComponents()[key]
			_ = val

			// no validation rules for Components[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, HealthStatusResponseValidationError{
							field:  fmt.Sprintf("Components[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, HealthStatusResponseValidationError{
							field:  fmt.Sprintf("Components[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return HealthStatusResponseValidationError{
						field:  fmt.Sprintf("Components[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return HealthStatusResponseMultiError(errors)
	}

	return nil
}

// HealthStatusResponseMultiError is an error wrapping multiple validation
// errors returned by HealthStatusResponse.ValidateAll() if the designated
// constraints aren't met.
type HealthStatusResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthStatusResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthStatusResponseMultiError) AllErrors() []error { return m }

// HealthStatusResponseValidationError is the validation error returned by
// HealthStatusResponse.Validate if the designated constraints aren't met.
type HealthStatusResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthStatusResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthStatusResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthStatusResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthStatusResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthStatusResponseValidationError) ErrorName() string {
	return "HealthStatusResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthStatusResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthStatusResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthStatusResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthStatusResponseValidationError{}

// Validate checks the field values on HealthStatusResponse_ComponentHealth
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *HealthStatusResponse_ComponentHealth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthStatusResponse_ComponentHealth
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// HealthStatusResponse_ComponentHealthMultiError, or nil if none found.
func (m *HealthStatusResponse_ComponentHealth) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthStatusResponse_ComponentHealth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Latency

	// no validation rules for Error

	if len(errors) > 0 {
		return HealthStatusResponse_ComponentHealthMultiError(errors)
	}

	return nil
}

// HealthStatusResponse_ComponentHealthMultiError is an error wrapping multiple
// validation errors returned by
// HealthStatusResponse_ComponentHealth.ValidateAll() if the designated
// constraints aren't met.
type HealthStatusResponse_ComponentHealthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthStatusResponse_ComponentHealthMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthStatusResponse_ComponentHealthMultiError) AllErrors() []error { return m }

// HealthStatusResponse_ComponentHealthValidationError is the validation error
// returned by HealthStatusResponse_ComponentHealth.Validate if the designated
// constraints aren't met.
type HealthStatusResponse_ComponentHealthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthStatusResponse_ComponentHealthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthStatusResponse_ComponentHealthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthStatusResponse_ComponentHealthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthStatusResponse_ComponentHealthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthStatusResponse_ComponentHealthValidationError) ErrorName() string {
	return "HealthStatusResponse_ComponentHealthValidationError"
}

// Error satisfies the builtin error interface
func (e HealthStatusResponse_ComponentHealthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthStatusResponse_ComponentHealth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthStatusResponse_ComponentHealthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthStatusResponse_ComponentHealthValidationError{}
