// Code generated by MockGen. DO NOT EDIT.
// Source: alarm.go
//
// Generated by this command:
//
//	mockgen -source=alarm.go -destination=./mocks/mock_alarm_message_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	data "github.com/seanbit/kratos/template/internal/data"
	gomock "go.uber.org/mock/gomock"
)

// MockIAlarmMessageRepo is a mock of IAlarmMessageRepo interface.
type MockIAlarmMessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAlarmMessageRepoMockRecorder
	isgomock struct{}
}

// MockIAlarmMessageRepoMockRecorder is the mock recorder for MockIAlarmMessageRepo.
type MockIAlarmMessageRepoMockRecorder struct {
	mock *MockIAlarmMessageRepo
}

// NewMockIAlarmMessageRepo creates a new mock instance.
func NewMockIAlarmMessageRepo(ctrl *gomock.Controller) *MockIAlarmMessageRepo {
	mock := &MockIAlarmMessageRepo{ctrl: ctrl}
	mock.recorder = &MockIAlarmMessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAlarmMessageRepo) EXPECT() *MockIAlarmMessageRepoMockRecorder {
	return m.recorder
}

// DequeueMessage mocks base method.
func (m *MockIAlarmMessageRepo) DequeueMessage(ctx context.Context) (*data.AlarmMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DequeueMessage", ctx)
	ret0, _ := ret[0].(*data.AlarmMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DequeueMessage indicates an expected call of DequeueMessage.
func (mr *MockIAlarmMessageRepoMockRecorder) DequeueMessage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DequeueMessage", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).DequeueMessage), ctx)
}

// EnqueueDelayedMessage mocks base method.
func (m *MockIAlarmMessageRepo) EnqueueDelayedMessage(ctx context.Context, msg *data.AlarmMessage, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueDelayedMessage", ctx, msg, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueDelayedMessage indicates an expected call of EnqueueDelayedMessage.
func (mr *MockIAlarmMessageRepoMockRecorder) EnqueueDelayedMessage(ctx, msg, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueDelayedMessage", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).EnqueueDelayedMessage), ctx, msg, delay)
}

// EnqueueMessage mocks base method.
func (m *MockIAlarmMessageRepo) EnqueueMessage(ctx context.Context, msg *data.AlarmMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueMessage indicates an expected call of EnqueueMessage.
func (mr *MockIAlarmMessageRepoMockRecorder) EnqueueMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueMessage", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).EnqueueMessage), ctx, msg)
}

// FuseMessage mocks base method.
func (m *MockIAlarmMessageRepo) FuseMessage(ctx context.Context, serviceName, message string, fuseDuration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FuseMessage", ctx, serviceName, message, fuseDuration)
	ret0, _ := ret[0].(error)
	return ret0
}

// FuseMessage indicates an expected call of FuseMessage.
func (mr *MockIAlarmMessageRepoMockRecorder) FuseMessage(ctx, serviceName, message, fuseDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FuseMessage", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).FuseMessage), ctx, serviceName, message, fuseDuration)
}

// IncrMessageTimes mocks base method.
func (m *MockIAlarmMessageRepo) IncrMessageTimes(ctx context.Context, serviceName, message string, cooldownTimes int, cacheIgnoreTime time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrMessageTimes", ctx, serviceName, message, cooldownTimes, cacheIgnoreTime)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrMessageTimes indicates an expected call of IncrMessageTimes.
func (mr *MockIAlarmMessageRepoMockRecorder) IncrMessageTimes(ctx, serviceName, message, cooldownTimes, cacheIgnoreTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrMessageTimes", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).IncrMessageTimes), ctx, serviceName, message, cooldownTimes, cacheIgnoreTime)
}

// IsIgnoreMessage mocks base method.
func (m *MockIAlarmMessageRepo) IsIgnoreMessage(serviceName, message string) (bool, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIgnoreMessage", serviceName, message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// IsIgnoreMessage indicates an expected call of IsIgnoreMessage.
func (mr *MockIAlarmMessageRepoMockRecorder) IsIgnoreMessage(serviceName, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIgnoreMessage", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).IsIgnoreMessage), serviceName, message)
}

// IsMessageFusing mocks base method.
func (m *MockIAlarmMessageRepo) IsMessageFusing(ctx context.Context, serviceName, message string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMessageFusing", ctx, serviceName, message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMessageFusing indicates an expected call of IsMessageFusing.
func (mr *MockIAlarmMessageRepoMockRecorder) IsMessageFusing(ctx, serviceName, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMessageFusing", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).IsMessageFusing), ctx, serviceName, message)
}

// ProcessDelayedMessages mocks base method.
func (m *MockIAlarmMessageRepo) ProcessDelayedMessages(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDelayedMessages", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessDelayedMessages indicates an expected call of ProcessDelayedMessages.
func (mr *MockIAlarmMessageRepoMockRecorder) ProcessDelayedMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDelayedMessages", reflect.TypeOf((*MockIAlarmMessageRepo)(nil).ProcessDelayedMessages), ctx)
}
