// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/seanbit/kratos/template/internal/data/model"
)

func newAlarmFilterWord(db *gorm.DB, opts ...gen.DOOption) alarmFilterWord {
	_alarmFilterWord := alarmFilterWord{}

	_alarmFilterWord.alarmFilterWordDo.UseDB(db, opts...)
	_alarmFilterWord.alarmFilterWordDo.UseModel(&model.AlarmFilterWord{})

	tableName := _alarmFilterWord.alarmFilterWordDo.TableName()
	_alarmFilterWord.ALL = field.NewAsterisk(tableName)
	_alarmFilterWord.ID = field.NewInt64(tableName, "id")
	_alarmFilterWord.Msg = field.NewString(tableName, "msg")
	_alarmFilterWord.Platform = field.NewString(tableName, "platform")
	_alarmFilterWord.CooldownTimes = field.NewInt32(tableName, "cooldown_times")

	_alarmFilterWord.fillFieldMap()

	return _alarmFilterWord
}

type alarmFilterWord struct {
	alarmFilterWordDo alarmFilterWordDo

	ALL           field.Asterisk
	ID            field.Int64
	Msg           field.String
	Platform      field.String
	CooldownTimes field.Int32

	fieldMap map[string]field.Expr
}

func (a alarmFilterWord) Table(newTableName string) *alarmFilterWord {
	a.alarmFilterWordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alarmFilterWord) As(alias string) *alarmFilterWord {
	a.alarmFilterWordDo.DO = *(a.alarmFilterWordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alarmFilterWord) updateTableName(table string) *alarmFilterWord {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Msg = field.NewString(table, "msg")
	a.Platform = field.NewString(table, "platform")
	a.CooldownTimes = field.NewInt32(table, "cooldown_times")

	a.fillFieldMap()

	return a
}

func (a *alarmFilterWord) WithContext(ctx context.Context) IAlarmFilterWordDo {
	return a.alarmFilterWordDo.WithContext(ctx)
}

func (a alarmFilterWord) TableName() string { return a.alarmFilterWordDo.TableName() }

func (a alarmFilterWord) Alias() string { return a.alarmFilterWordDo.Alias() }

func (a alarmFilterWord) Columns(cols ...field.Expr) gen.Columns {
	return a.alarmFilterWordDo.Columns(cols...)
}

func (a *alarmFilterWord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alarmFilterWord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["id"] = a.ID
	a.fieldMap["msg"] = a.Msg
	a.fieldMap["platform"] = a.Platform
	a.fieldMap["cooldown_times"] = a.CooldownTimes
}

func (a alarmFilterWord) clone(db *gorm.DB) alarmFilterWord {
	a.alarmFilterWordDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alarmFilterWord) replaceDB(db *gorm.DB) alarmFilterWord {
	a.alarmFilterWordDo.ReplaceDB(db)
	return a
}

type alarmFilterWordDo struct{ gen.DO }

type IAlarmFilterWordDo interface {
	gen.SubQuery
	Debug() IAlarmFilterWordDo
	WithContext(ctx context.Context) IAlarmFilterWordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlarmFilterWordDo
	WriteDB() IAlarmFilterWordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlarmFilterWordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlarmFilterWordDo
	Not(conds ...gen.Condition) IAlarmFilterWordDo
	Or(conds ...gen.Condition) IAlarmFilterWordDo
	Select(conds ...field.Expr) IAlarmFilterWordDo
	Where(conds ...gen.Condition) IAlarmFilterWordDo
	Order(conds ...field.Expr) IAlarmFilterWordDo
	Distinct(cols ...field.Expr) IAlarmFilterWordDo
	Omit(cols ...field.Expr) IAlarmFilterWordDo
	Join(table schema.Tabler, on ...field.Expr) IAlarmFilterWordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlarmFilterWordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlarmFilterWordDo
	Group(cols ...field.Expr) IAlarmFilterWordDo
	Having(conds ...gen.Condition) IAlarmFilterWordDo
	Limit(limit int) IAlarmFilterWordDo
	Offset(offset int) IAlarmFilterWordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlarmFilterWordDo
	Unscoped() IAlarmFilterWordDo
	Create(values ...*model.AlarmFilterWord) error
	CreateInBatches(values []*model.AlarmFilterWord, batchSize int) error
	Save(values ...*model.AlarmFilterWord) error
	First() (*model.AlarmFilterWord, error)
	Take() (*model.AlarmFilterWord, error)
	Last() (*model.AlarmFilterWord, error)
	Find() ([]*model.AlarmFilterWord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlarmFilterWord, err error)
	FindInBatches(result *[]*model.AlarmFilterWord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlarmFilterWord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlarmFilterWordDo
	Assign(attrs ...field.AssignExpr) IAlarmFilterWordDo
	Joins(fields ...field.RelationField) IAlarmFilterWordDo
	Preload(fields ...field.RelationField) IAlarmFilterWordDo
	FirstOrInit() (*model.AlarmFilterWord, error)
	FirstOrCreate() (*model.AlarmFilterWord, error)
	FindByPage(offset int, limit int) (result []*model.AlarmFilterWord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlarmFilterWordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alarmFilterWordDo) Debug() IAlarmFilterWordDo {
	return a.withDO(a.DO.Debug())
}

func (a alarmFilterWordDo) WithContext(ctx context.Context) IAlarmFilterWordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alarmFilterWordDo) ReadDB() IAlarmFilterWordDo {
	return a.Clauses(dbresolver.Read)
}

func (a alarmFilterWordDo) WriteDB() IAlarmFilterWordDo {
	return a.Clauses(dbresolver.Write)
}

func (a alarmFilterWordDo) Session(config *gorm.Session) IAlarmFilterWordDo {
	return a.withDO(a.DO.Session(config))
}

func (a alarmFilterWordDo) Clauses(conds ...clause.Expression) IAlarmFilterWordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alarmFilterWordDo) Returning(value interface{}, columns ...string) IAlarmFilterWordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alarmFilterWordDo) Not(conds ...gen.Condition) IAlarmFilterWordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alarmFilterWordDo) Or(conds ...gen.Condition) IAlarmFilterWordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alarmFilterWordDo) Select(conds ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alarmFilterWordDo) Where(conds ...gen.Condition) IAlarmFilterWordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alarmFilterWordDo) Order(conds ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alarmFilterWordDo) Distinct(cols ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alarmFilterWordDo) Omit(cols ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alarmFilterWordDo) Join(table schema.Tabler, on ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alarmFilterWordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alarmFilterWordDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alarmFilterWordDo) Group(cols ...field.Expr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alarmFilterWordDo) Having(conds ...gen.Condition) IAlarmFilterWordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alarmFilterWordDo) Limit(limit int) IAlarmFilterWordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alarmFilterWordDo) Offset(offset int) IAlarmFilterWordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alarmFilterWordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlarmFilterWordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alarmFilterWordDo) Unscoped() IAlarmFilterWordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alarmFilterWordDo) Create(values ...*model.AlarmFilterWord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alarmFilterWordDo) CreateInBatches(values []*model.AlarmFilterWord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alarmFilterWordDo) Save(values ...*model.AlarmFilterWord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alarmFilterWordDo) First() (*model.AlarmFilterWord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlarmFilterWord), nil
	}
}

func (a alarmFilterWordDo) Take() (*model.AlarmFilterWord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlarmFilterWord), nil
	}
}

func (a alarmFilterWordDo) Last() (*model.AlarmFilterWord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlarmFilterWord), nil
	}
}

func (a alarmFilterWordDo) Find() ([]*model.AlarmFilterWord, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlarmFilterWord), err
}

func (a alarmFilterWordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlarmFilterWord, err error) {
	buf := make([]*model.AlarmFilterWord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alarmFilterWordDo) FindInBatches(result *[]*model.AlarmFilterWord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alarmFilterWordDo) Attrs(attrs ...field.AssignExpr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alarmFilterWordDo) Assign(attrs ...field.AssignExpr) IAlarmFilterWordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alarmFilterWordDo) Joins(fields ...field.RelationField) IAlarmFilterWordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alarmFilterWordDo) Preload(fields ...field.RelationField) IAlarmFilterWordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alarmFilterWordDo) FirstOrInit() (*model.AlarmFilterWord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlarmFilterWord), nil
	}
}

func (a alarmFilterWordDo) FirstOrCreate() (*model.AlarmFilterWord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlarmFilterWord), nil
	}
}

func (a alarmFilterWordDo) FindByPage(offset int, limit int) (result []*model.AlarmFilterWord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alarmFilterWordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alarmFilterWordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alarmFilterWordDo) Delete(models ...*model.AlarmFilterWord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alarmFilterWordDo) withDO(do gen.Dao) *alarmFilterWordDo {
	a.DO = *do.(*gen.DO)
	return a
}
