// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/seanbit/kratos/template/internal/biz"
	"github.com/seanbit/kratos/template/internal/conf"
	"github.com/seanbit/kratos/template/internal/data"
	"github.com/seanbit/kratos/template/internal/infra"
	"github.com/seanbit/kratos/template/internal/server"
	"github.com/seanbit/kratos/template/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, s3 *conf.S3, geoIp *conf.GeoIp, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataProvider, cleanup, err := infra.NewDataProvider(confData)
	if err != nil {
		return nil, nil, err
	}
	iAuthRepo := data.NewAuthRepo(dataProvider, dataProvider)
	client, err := server.NewAsynqClient(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iAuthLogRepo := data.NewAuthLogRepo(dataProvider, dataProvider, client)
	s3Client := infra.NewS3Client(s3)
	iGeoIp, err := data.NewGeoIP(s3Client, geoIp)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bizAuth := biz.NewAuth(auth, iAuthRepo, iAuthLogRepo, iGeoIp)
	eventHandlerServer := service.NewEventService(bizAuth)
	asynqServer := server.NewAsynqServer(confServer, logger, eventHandlerServer)
	httpServer := server.NewMetricsServer()
	app := newApp(asynqServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
