// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"evm-scan/cmd/job/jobs"
	"evm-scan/internal/biz"
	"evm-scan/internal/biz/processor"
	"evm-scan/internal/conf"
	"evm-scan/internal/data"
	"evm-scan/internal/infra"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp 初始化应用依赖
func initApp(server *conf.Server, confData *conf.Data, blockchain *conf.Blockchain, scanner *conf.Scanner, logger log.Logger) (*jobs.App, func(), error) {
	dataProvider, cleanup, err := infra.NewDataProvider(confData)
	if err != nil {
		return nil, nil, err
	}
	iEventRepo := data.NewEventRepo(dataProvider, logger)
	iErc20TransferRepo := data.NewErc20TransferRepo(dataProvider, logger)
	iErc20BalanceRepo := data.NewErc20BalanceRepo(dataProvider, logger)
	iScanProgressRepo := data.NewScanProgressRepo(dataProvider, logger)
	erc20Processor := processor.NewERC20Processor(iErc20TransferRepo, iErc20BalanceRepo, iScanProgressRepo, logger)
	iLafStakingRepo := data.NewLafStakingRepo(dataProvider, logger)
	lafStakingProcessor := processor.NewLafStakingProcessor(iLafStakingRepo, logger)
	v := processor.ProvideProcessors(erc20Processor, lafStakingProcessor)
	iProcessorConfigRepo := data.NewProcessorConfigRepo(dataProvider, logger)
	eventDispatcher := processor.NewEventDispatcher(v, iProcessorConfigRepo, logger)
	app := newJobApp(iEventRepo, eventDispatcher)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// newJobApp 创建 Job App
func newJobApp(
	eventRepo biz.IEventRepo,
	eventDispatcher biz.IEventDispatcher,
) *jobs.App {
	return &jobs.App{
		EventRepo:       eventRepo,
		EventDispatcher: eventDispatcher,
	}
}
