// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"

	"github.com/seanbit/kratos/template/cmd/job/jobs"
	"github.com/seanbit/kratos/template/internal/conf"
)

// Injectors from wire.go:

// initApp 初始化应用依赖
func initApp(confData *conf.Data, logger log.Logger) (*jobs.App, func(), error) {
	app := newJobApp(logger)
	return app, func() {}, nil
}

// wire.go:

// newJobApp 创建 Job App
func newJobApp(logger log.Logger) *jobs.App {
	return &jobs.App{
		Logger: logger,
	}
}
