// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 环境配置枚举
type Env int32

const (
	// 本地调试
	Env_LOCAL Env = 0
	// 开发环境
	Env_DEV Env = 1
	// 测试环境
	Env_TEST Env = 2
	// 生产环境
	Env_PROD Env = 3
)

// Enum value maps for Env.
var (
	Env_name = map[int32]string{
		0: "LOCAL",
		1: "DEV",
		2: "TEST",
		3: "PROD",
	}
	Env_value = map[string]int32{
		"LOCAL": 0,
		"DEV":   1,
		"TEST":  2,
		"PROD":  3,
	}
)

func (x Env) Enum() *Env {
	p := new(Env)
	*p = x
	return p
}

func (x Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Env) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Env) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Env.Descriptor instead.
func (Env) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

type LogLevel int32

const (
	LogLevel_Debug LogLevel = 0
	LogLevel_Info  LogLevel = 1
	LogLevel_Warn  LogLevel = 2
	LogLevel_Error LogLevel = 3
	LogLevel_Fatal LogLevel = 4
	LogLevel_Panic LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "Debug",
		1: "Info",
		2: "Warn",
		3: "Error",
		4: "Fatal",
		5: "Panic",
	}
	LogLevel_value = map[string]int32{
		"Debug": 0,
		"Info":  1,
		"Warn":  2,
		"Error": 3,
		"Fatal": 4,
		"Panic": 5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Env           Env                    `protobuf:"varint,3,opt,name=env,proto3,enum=kratos.api.Env" json:"env,omitempty"`
	LogLevel      LogLevel               `protobuf:"varint,4,opt,name=log_level,json=logLevel,proto3,enum=kratos.api.LogLevel" json:"log_level,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Sentry        *Sentry                `protobuf:"bytes,6,opt,name=sentry,proto3" json:"sentry,omitempty"`
	Tracing       *Tracing               `protobuf:"bytes,7,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Alarm         *Alarm                 `protobuf:"bytes,8,opt,name=alarm,proto3" json:"alarm,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,9,opt,name=auth,proto3" json:"auth,omitempty"`
	S3            *S3                    `protobuf:"bytes,10,opt,name=s3,proto3" json:"s3,omitempty"`
	GeoIp         *GeoIp                 `protobuf:"bytes,11,opt,name=geo_ip,json=geoIp,proto3" json:"geo_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetEnv() Env {
	if x != nil {
		return x.Env
	}
	return Env_LOCAL
}

func (x *Bootstrap) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_Debug
}

func (x *Bootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bootstrap) GetSentry() *Sentry {
	if x != nil {
		return x.Sentry
	}
	return nil
}

func (x *Bootstrap) GetTracing() *Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Bootstrap) GetAlarm() *Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetS3() *S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *Bootstrap) GetGeoIp() *GeoIp {
	if x != nil {
		return x.GeoIp
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Asynq         *Server_ASYNQ          `protobuf:"bytes,3,opt,name=asynq,proto3" json:"asynq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetAsynq() *Server_ASYNQ {
	if x != nil {
		return x.Asynq
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Tracing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Tracing) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Tracing) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Tracing) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Sentry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Dsn              string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	AttachStackTrace bool                   `protobuf:"varint,2,opt,name=attach_stack_trace,json=attachStackTrace,proto3" json:"attach_stack_trace,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Sentry) Reset() {
	*x = Sentry{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sentry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sentry) ProtoMessage() {}

func (x *Sentry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sentry.ProtoReflect.Descriptor instead.
func (*Sentry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Sentry) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Sentry) GetAttachStackTrace() bool {
	if x != nil {
		return x.AttachStackTrace
	}
	return false
}

type Alarm struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WebHooks            map[string]string      `protobuf:"bytes,1,rep,name=web_hooks,json=webHooks,proto3" json:"web_hooks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CacheIgnoreDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=cache_ignore_duration,json=cacheIgnoreDuration,proto3" json:"cache_ignore_duration,omitempty"`
	CacheFuseDuration   *durationpb.Duration   `protobuf:"bytes,3,opt,name=cache_fuse_duration,json=cacheFuseDuration,proto3" json:"cache_fuse_duration,omitempty"`
	DefaultPlatform     string                 `protobuf:"bytes,4,opt,name=default_platform,json=defaultPlatform,proto3" json:"default_platform,omitempty"`
	DryRun              bool                   `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Concurrency         int32                  `protobuf:"varint,6,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Alarm) GetWebHooks() map[string]string {
	if x != nil {
		return x.WebHooks
	}
	return nil
}

func (x *Alarm) GetCacheIgnoreDuration() *durationpb.Duration {
	if x != nil {
		return x.CacheIgnoreDuration
	}
	return nil
}

func (x *Alarm) GetCacheFuseDuration() *durationpb.Duration {
	if x != nil {
		return x.CacheFuseDuration
	}
	return nil
}

func (x *Alarm) GetDefaultPlatform() string {
	if x != nil {
		return x.DefaultPlatform
	}
	return ""
}

func (x *Alarm) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *Alarm) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtKey_25519  string                 `protobuf:"bytes,1,opt,name=jwt_key_25519,json=jwtKey25519,proto3" json:"jwt_key_25519,omitempty"`
	LoginExpires  *durationpb.Duration   `protobuf:"bytes,2,opt,name=login_expires,json=loginExpires,proto3" json:"login_expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Auth) GetJwtKey_25519() string {
	if x != nil {
		return x.JwtKey_25519
	}
	return ""
}

func (x *Auth) GetLoginExpires() *durationpb.Duration {
	if x != nil {
		return x.LoginExpires
	}
	return nil
}

type Cos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Host          string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cos) Reset() {
	*x = Cos{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cos) ProtoMessage() {}

func (x *Cos) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cos.ProtoReflect.Descriptor instead.
func (*Cos) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Cos) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *Cos) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Cos) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Cos) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Cos) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type S3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Host          string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3) Reset() {
	*x = S3{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3) ProtoMessage() {}

func (x *S3) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3.ProtoReflect.Descriptor instead.
func (*S3) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *S3) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *S3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GeoIp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileBucket    string                 `protobuf:"bytes,1,opt,name=file_bucket,json=fileBucket,proto3" json:"file_bucket,omitempty"`
	FileKey       string                 `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoIp) Reset() {
	*x = GeoIp{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoIp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoIp) ProtoMessage() {}

func (x *GeoIp) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoIp.ProtoReflect.Descriptor instead.
func (*GeoIp) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *GeoIp) GetFileBucket() string {
	if x != nil {
		return x.FileBucket
	}
	return ""
}

func (x *GeoIp) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_ASYNQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedisUri      string                 `protobuf:"bytes,1,opt,name=redis_uri,json=redisUri,proto3" json:"redis_uri,omitempty"`
	Queues        map[string]int32       `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Concurrency   int32                  `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_ASYNQ) Reset() {
	*x = Server_ASYNQ{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_ASYNQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_ASYNQ) ProtoMessage() {}

func (x *Server_ASYNQ) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_ASYNQ.ProtoReflect.Descriptor instead.
func (*Server_ASYNQ) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Server_ASYNQ) GetRedisUri() string {
	if x != nil {
		return x.RedisUri
	}
	return ""
}

func (x *Server_ASYNQ) GetQueues() map[string]int32 {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *Server_ASYNQ) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type Data_Database struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Driver             string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	SlavesDsn          []string               `protobuf:"bytes,2,rep,name=slaves_dsn,json=slavesDsn,proto3" json:"slaves_dsn,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MaxOpenConnections int32                  `protobuf:"varint,4,opt,name=max_open_connections,json=maxOpenConnections,proto3" json:"max_open_connections,omitempty"`
	MaxIdleConnections int32                  `protobuf:"varint,5,opt,name=max_idle_connections,json=maxIdleConnections,proto3" json:"max_idle_connections,omitempty"`
	ConnMaxLifetime    *durationpb.Duration   `protobuf:"bytes,6,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime    *durationpb.Duration   `protobuf:"bytes,7,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	DefaultSchema      string                 `protobuf:"bytes,8,opt,name=default_schema,json=defaultSchema,proto3" json:"default_schema,omitempty"`
	GormLevel          int32                  `protobuf:"varint,9,opt,name=gorm_level,json=gormLevel,proto3" json:"gorm_level,omitempty"`              // 4-info  3-warn
	SlowThreshold      int32                  `protobuf:"varint,10,opt,name=slow_threshold,json=slowThreshold,proto3" json:"slow_threshold,omitempty"` // unit: millisecond
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSlavesDsn() []string {
	if x != nil {
		return x.SlavesDsn
	}
	return nil
}

func (x *Data_Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data_Database) GetMaxOpenConnections() int32 {
	if x != nil {
		return x.MaxOpenConnections
	}
	return 0
}

func (x *Data_Database) GetMaxIdleConnections() int32 {
	if x != nil {
		return x.MaxIdleConnections
	}
	return 0
}

func (x *Data_Database) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

func (x *Data_Database) GetConnMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return nil
}

func (x *Data_Database) GetDefaultSchema() string {
	if x != nil {
		return x.DefaultSchema
	}
	return ""
}

func (x *Data_Database) GetGormLevel() int32 {
	if x != nil {
		return x.GormLevel
	}
	return 0
}

func (x *Data_Database) GetSlowThreshold() int32 {
	if x != nil {
		return x.SlowThreshold
	}
	return 0
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCluster     bool                   `protobuf:"varint,1,opt,name=is_cluster,json=isCluster,proto3" json:"is_cluster,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Db            int32                  `protobuf:"varint,5,opt,name=db,proto3" json:"db,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	PoolSize      uint32                 `protobuf:"varint,8,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	MinIdleConn   uint32                 `protobuf:"varint,9,opt,name=min_idle_conn,json=minIdleConn,proto3" json:"min_idle_conn,omitempty"`
	MaxRetryTimes uint32                 `protobuf:"varint,10,opt,name=max_retry_times,json=maxRetryTimes,proto3" json:"max_retry_times,omitempty"`
	IdleTimeout   *durationpb.Duration   `protobuf:"bytes,11,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetIsCluster() bool {
	if x != nil {
		return x.IsCluster
	}
	return false
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *Data_Redis) GetMinIdleConn() uint32 {
	if x != nil {
		return x.MinIdleConn
	}
	return 0
}

func (x *Data_Redis) GetMaxRetryTimes() uint32 {
	if x != nil {
		return x.MaxRetryTimes
	}
	return 0
}

func (x *Data_Redis) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xbb\x03\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12!\n" +
	"\x03env\x18\x03 \x01(\x0e2\x0f.kratos.api.EnvR\x03env\x121\n" +
	"\tlog_level\x18\x04 \x01(\x0e2\x14.kratos.api.LogLevelR\blogLevel\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12*\n" +
	"\x06sentry\x18\x06 \x01(\v2\x12.kratos.api.SentryR\x06sentry\x12-\n" +
	"\atracing\x18\a \x01(\v2\x13.kratos.api.TracingR\atracing\x12'\n" +
	"\x05alarm\x18\b \x01(\v2\x11.kratos.api.AlarmR\x05alarm\x12$\n" +
	"\x04auth\x18\t \x01(\v2\x10.kratos.api.AuthR\x04auth\x12\x1e\n" +
	"\x02s3\x18\n" +
	" \x01(\v2\x0e.kratos.api.S3R\x02s3\x12(\n" +
	"\x06geo_ip\x18\v \x01(\v2\x11.kratos.api.GeoIpR\x05geoIp\"\xaa\x04\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x12.\n" +
	"\x05asynq\x18\x03 \x01(\v2\x18.kratos.api.Server.ASYNQR\x05asynq\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a\xbf\x01\n" +
	"\x05ASYNQ\x12\x1b\n" +
	"\tredis_uri\x18\x01 \x01(\tR\bredisUri\x12<\n" +
	"\x06queues\x18\x02 \x03(\v2$.kratos.api.Server.ASYNQ.QueuesEntryR\x06queues\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\x05R\vconcurrency\x1a9\n" +
	"\vQueuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xcd\a\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\xb5\x03\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x1d\n" +
	"\n" +
	"slaves_dsn\x18\x02 \x03(\tR\tslavesDsn\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x120\n" +
	"\x14max_open_connections\x18\x04 \x01(\x05R\x12maxOpenConnections\x120\n" +
	"\x14max_idle_connections\x18\x05 \x01(\x05R\x12maxIdleConnections\x12E\n" +
	"\x11conn_max_lifetime\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x12F\n" +
	"\x12conn_max_idle_time\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxIdleTime\x12%\n" +
	"\x0edefault_schema\x18\b \x01(\tR\rdefaultSchema\x12\x1d\n" +
	"\n" +
	"gorm_level\x18\t \x01(\x05R\tgormLevel\x12%\n" +
	"\x0eslow_threshold\x18\n" +
	" \x01(\x05R\rslowThreshold\x1a\xa7\x03\n" +
	"\x05Redis\x12\x1d\n" +
	"\n" +
	"is_cluster\x18\x01 \x01(\bR\tisCluster\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x0e\n" +
	"\x02db\x18\x05 \x01(\x05R\x02db\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x1b\n" +
	"\tpool_size\x18\b \x01(\rR\bpoolSize\x12\"\n" +
	"\rmin_idle_conn\x18\t \x01(\rR\vminIdleConn\x12&\n" +
	"\x0fmax_retry_times\x18\n" +
	" \x01(\rR\rmaxRetryTimes\x12<\n" +
	"\fidle_timeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\vidleTimeout\"E\n" +
	"\aTracing\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"H\n" +
	"\x06Sentry\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12,\n" +
	"\x12attach_stack_trace\x18\x02 \x01(\bR\x10attachStackTrace\"\x82\x03\n" +
	"\x05Alarm\x12<\n" +
	"\tweb_hooks\x18\x01 \x03(\v2\x1f.kratos.api.Alarm.WebHooksEntryR\bwebHooks\x12M\n" +
	"\x15cache_ignore_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x13cacheIgnoreDuration\x12I\n" +
	"\x13cache_fuse_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11cacheFuseDuration\x12)\n" +
	"\x10default_platform\x18\x04 \x01(\tR\x0fdefaultPlatform\x12\x17\n" +
	"\adry_run\x18\x05 \x01(\bR\x06dryRun\x12 \n" +
	"\vconcurrency\x18\x06 \x01(\x05R\vconcurrency\x1a;\n" +
	"\rWebHooksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x04Auth\x12\"\n" +
	"\rjwt_key_25519\x18\x01 \x01(\tR\vjwtKey25519\x12>\n" +
	"\rlogin_expires\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\floginExpires\"\x85\x01\n" +
	"\x03Cos\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\"\x86\x01\n" +
	"\x02S3\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\"C\n" +
	"\x05GeoIp\x12\x1f\n" +
	"\vfile_bucket\x18\x01 \x01(\tR\n" +
	"fileBucket\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey*-\n" +
	"\x03Env\x12\t\n" +
	"\x05LOCAL\x10\x00\x12\a\n" +
	"\x03DEV\x10\x01\x12\b\n" +
	"\x04TEST\x10\x02\x12\b\n" +
	"\x04PROD\x10\x03*J\n" +
	"\bLogLevel\x12\t\n" +
	"\x05Debug\x10\x00\x12\b\n" +
	"\x04Info\x10\x01\x12\b\n" +
	"\x04Warn\x10\x02\x12\t\n" +
	"\x05Error\x10\x03\x12\t\n" +
	"\x05Fatal\x10\x04\x12\t\n" +
	"\x05Panic\x10\x05B\x18Z\x16web/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_conf_conf_proto_goTypes = []any{
	(Env)(0),                    // 0: kratos.api.Env
	(LogLevel)(0),               // 1: kratos.api.LogLevel
	(*Bootstrap)(nil),           // 2: kratos.api.Bootstrap
	(*Server)(nil),              // 3: kratos.api.Server
	(*Data)(nil),                // 4: kratos.api.Data
	(*Tracing)(nil),             // 5: kratos.api.Tracing
	(*Sentry)(nil),              // 6: kratos.api.Sentry
	(*Alarm)(nil),               // 7: kratos.api.Alarm
	(*Auth)(nil),                // 8: kratos.api.Auth
	(*Cos)(nil),                 // 9: kratos.api.Cos
	(*S3)(nil),                  // 10: kratos.api.S3
	(*GeoIp)(nil),               // 11: kratos.api.GeoIp
	(*Server_HTTP)(nil),         // 12: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 13: kratos.api.Server.GRPC
	(*Server_ASYNQ)(nil),        // 14: kratos.api.Server.ASYNQ
	nil,                         // 15: kratos.api.Server.ASYNQ.QueuesEntry
	(*Data_Database)(nil),       // 16: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 17: kratos.api.Data.Redis
	nil,                         // 18: kratos.api.Alarm.WebHooksEntry
	(*durationpb.Duration)(nil), // 19: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	3,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	4,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	0,  // 2: kratos.api.Bootstrap.env:type_name -> kratos.api.Env
	1,  // 3: kratos.api.Bootstrap.log_level:type_name -> kratos.api.LogLevel
	6,  // 4: kratos.api.Bootstrap.sentry:type_name -> kratos.api.Sentry
	5,  // 5: kratos.api.Bootstrap.tracing:type_name -> kratos.api.Tracing
	7,  // 6: kratos.api.Bootstrap.alarm:type_name -> kratos.api.Alarm
	8,  // 7: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	10, // 8: kratos.api.Bootstrap.s3:type_name -> kratos.api.S3
	11, // 9: kratos.api.Bootstrap.geo_ip:type_name -> kratos.api.GeoIp
	12, // 10: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	13, // 11: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	14, // 12: kratos.api.Server.asynq:type_name -> kratos.api.Server.ASYNQ
	16, // 13: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	17, // 14: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	18, // 15: kratos.api.Alarm.web_hooks:type_name -> kratos.api.Alarm.WebHooksEntry
	19, // 16: kratos.api.Alarm.cache_ignore_duration:type_name -> google.protobuf.Duration
	19, // 17: kratos.api.Alarm.cache_fuse_duration:type_name -> google.protobuf.Duration
	19, // 18: kratos.api.Auth.login_expires:type_name -> google.protobuf.Duration
	19, // 19: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	19, // 20: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	15, // 21: kratos.api.Server.ASYNQ.queues:type_name -> kratos.api.Server.ASYNQ.QueuesEntry
	19, // 22: kratos.api.Data.Database.conn_max_lifetime:type_name -> google.protobuf.Duration
	19, // 23: kratos.api.Data.Database.conn_max_idle_time:type_name -> google.protobuf.Duration
	19, // 24: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	19, // 25: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	19, // 26: kratos.api.Data.Redis.idle_timeout:type_name -> google.protobuf.Duration
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
