// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"evm-scan/internal/conf"
	"evm-scan/internal/crontab"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(cronJob *conf.CronJob, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	jobTest := crontab.NewJobTest()
	jobRegister := crontab.NewJobRegister(cronJob, jobTest)
	executor := crontab.NewCrontabExecutor(jobRegister)
	app := newApp(executor)
	return app, func() {
	}, nil
}
