// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserLoginLog = "index_backend.user_login_log"

// UserLoginLog mapped from table <index_backend.user_login_log>
type UserLoginLog struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID      string    `gorm:"column:user_id;type:character varying(64);not null" json:"user_id"`
	AuthType    string    `gorm:"column:auth_type;type:character varying(32);not null" json:"auth_type"`
	IssueToken  string    `gorm:"column:issue_token;type:text" json:"issue_token"`
	IP          string    `gorm:"column:ip;type:inet" json:"ip"`
	Country     string    `gorm:"column:country;type:character varying(255);not null" json:"country"`
	CreatedTime time.Time `gorm:"column:created_time;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"updated_time"`
}

// TableName UserLoginLog's table name
func (*UserLoginLog) TableName() string {
	return TableNameUserLoginLog
}
