// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlarmFilterWord = "index_backend.alarm_filter_word"

// AlarmFilterWord mapped from table <index_backend.alarm_filter_word>
type AlarmFilterWord struct {
	ID            int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Msg           string `gorm:"column:msg;type:character varying(255);not null" json:"msg"`
	Platform      string `gorm:"column:platform;type:character varying(50);not null;default:carv-backend" json:"platform"`
	CooldownTimes int32  `gorm:"column:cooldown_times;type:integer;not null;default:50" json:"cooldown_times"`
}

// TableName AlarmFilterWord's table name
func (*AlarmFilterWord) TableName() string {
	return TableNameAlarmFilterWord
}
