// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAuthInfo = "index_backend.user_auth_info"

// UserAuthInfo mapped from table <index_backend.user_auth_info>
type UserAuthInfo struct {
	ID        int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:user_id;type:character varying(64);not null" json:"user_id"`
	AuthType  string    `gorm:"column:auth_type;type:character varying(32);not null" json:"auth_type"`
	AuthInfo  string    `gorm:"column:auth_info;type:character varying(64);not null" json:"auth_info"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserAuthInfo's table name
func (*UserAuthInfo) TableName() string {
	return TableNameUserAuthInfo
}
