// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/seanbit/kratos/template/internal/biz"
	"github.com/seanbit/kratos/template/internal/conf"
	"github.com/seanbit/kratos/template/internal/crontab"
	"github.com/seanbit/kratos/template/internal/data"
	"github.com/seanbit/kratos/template/internal/infra"
	"github.com/seanbit/kratos/template/internal/server"
	"github.com/seanbit/kratos/template/internal/server/middlewares"
	"github.com/seanbit/kratos/template/internal/service"
	crontab2 "github.com/seanbit/kratos/webkit/transport/crontab"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, s3 *conf.S3, geoIp *conf.GeoIp, alarm *conf.Alarm, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	probe := biz.NewProbe()
	probeService := service.NewProbeService(probe)
	grpcServer := server.NewGRPCServer(confServer, probeService, logger)
	dataProvider, cleanup, err := infra.NewDataProvider(confData)
	if err != nil {
		return nil, nil, err
	}
	iAuthRepo := data.NewAuthRepo(dataProvider, dataProvider)
	client, err := server.NewAsynqClient(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iAuthLogRepo := data.NewAuthLogRepo(dataProvider, dataProvider, client)
	s3Client := infra.NewS3Client(s3)
	iGeoIp, err := data.NewGeoIP(s3Client, geoIp)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bizAuth := biz.NewAuth(auth, iAuthRepo, iAuthLogRepo, iGeoIp)
	userAuth := middlewares.NewUserAuth(bizAuth)
	httpBuilder := middlewares.NewHttpBuilder(userAuth)
	iAlarmMessageRepo := data.NewAlarmMessageRepo(dataProvider, dataProvider, logger)
	iAlarmRepo, cleanup2, err := data.NewAlarm(alarm, iAlarmMessageRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(bizAuth)
	httpServer := server.NewHTTPServer(confServer, logger, httpBuilder, probeService, iAlarmRepo, authService)
	eventHandlerServer := service.NewEventService(bizAuth)
	asynqServer := server.NewAsynqServer(confServer, logger, eventHandlerServer)
	jobTest := crontab.NewJobTest()
	jobRegister := crontab.NewJobRegister(jobTest)
	executor := crontab2.NewServer(jobRegister)
	app := newApp(grpcServer, httpServer, asynqServer, executor)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
